/* Return to Self static sets: v1 (16 Sep 2026, A1–A3 / C1–C8) and v2 (17 Sep 2026, A4 / C9–C18, below).
   v1 — 16 Sep 2026.
   One board per video from Nathan's shoot: three ad concepts (hook-matched
   variants) and eight content pieces. Copy is verbatim from the transcripts
   except A1.4's sub and C6's headline, which are paraphrases awaiting sign-off.
   `bg` names a built-in still in assets/statics (photo top, ink below). */
window.__RTS_STATICS__ = [
  /* ---- Static set v2 — self-worth, 17 Sep 2026.
     Eighteen boards on the 26 Aug production-day stills (shoji room, the match), copy verbatim from
     Harrison's Sep 1 / Sep 8 organic pieces (self-worth, unappreciated, solving problems, proving
     yourself, sin of greed, breathing wrong). Lines marked ~ are trimmed or cleaned and need his
     sign-off: A4.2 sub, A4.4 head, A4.8 head, C10 head, C16 both. Type boards reuse the temple-ink plate. */
  { id: 'A4.1', name: 'Your value doesn’t disappear', layout: 'cover', bg: 'rtsA41', kicker: 'Return to Self',
    head: 'Your value doesn’t disappear when you don’t work, perform or try.',
    sub: 'Self-worth is an ongoing feeling that you’re enough.',
    cta: 'See how the 12 weeks work' },
  { id: 'A4.2', name: 'Self-worth is a feeling', layout: 'cover', bg: 'rtsA42', kicker: 'Return to Self',
    head: 'Self-worth, at the end of the day, is a feeling.',
    sub: 'No amount of numbers or external things outside of yourself will give you that feeling.',
    cta: 'See how the 12 weeks work' },
  { id: 'A4.3', name: 'Unappreciated', layout: 'cover', bg: 'rtsA43', kicker: 'Return to Self',
    head: 'Do you feel unappreciated even though you try so hard?',
    sub: 'It’s not about them. Subconsciously, you may still be tying your self-worth to your achievements.',
    cta: 'See how the 12 weeks work' },
  { id: 'A4.4', name: 'Outwork all your problems', layout: 'cover', bg: 'rtsA44', kicker: 'Return to Self',
    head: 'My narrative was: outwork all your problems.',
    sub: 'And what did that lead to? Breakdown. Burnout. Nothing ever felt enough.',
    cta: 'See how the 12 weeks work' },
  { id: 'A4.5', name: 'Urge to prove something', layout: 'cover', bg: 'rtsA45', kicker: 'Return to Self',
    head: 'Do you feel a strong urge to prove something?',
    sub: 'I was just trying to protect my ego and get a sense of worth.',
    cta: 'See how the 12 weeks work' },
  { id: 'A4.6', name: 'You deserve to feel self-worth', layout: 'cover', bg: 'rtsA46', kicker: 'Return to Self',
    head: 'You deserve to feel self-worth.',
    sub: 'Measurement is helpful, but it shouldn’t dictate your whole life and how you feel day to day.',
    cta: 'See how the 12 weeks work' },
  { id: 'A4.7', name: 'I see you', layout: 'type', bg: 'rtsC7', kicker: 'Return to Self',
    head: 'I see you. You’re doing enough.',
    sub: 'Keep going. It’s up to you to tell yourself that each moment, each day.',
    cta: 'See how the 12 weeks work' },
  { id: 'A4.8', name: 'Nothing felt enough', layout: 'cover', bg: 'rtsA48', kicker: 'Return to Self',
    head: 'No amount of work, 10, 12 hour days, 7 days a week, felt enough.',
    sub: 'Now more than ever it’s important we feel like we’re enough.',
    cta: 'See how the 12 weeks work' },
  { id: 'C9', name: 'So convenient to measure', layout: 'cover', bg: 'rtsC9', kicker: '',
    head: 'It’s so convenient to measure all the time.',
    sub: 'Measure your self-worth and attribute it to things like income, net worth, rankings, KPIs, performance.', cta: '' },
  { id: 'C10', name: 'Worthy of love', layout: 'cover', bg: 'rtsC10', kicker: '',
    head: 'I learned that the problems I solved, and how quickly I solved them, linked to self-worth. That I am worthy of love.',
    sub: 'Three divorced parents, and a Japanese traditional father who was 54 years older than me.', cta: '' },
  { id: 'C11', name: 'The sin of greed', layout: 'archival', bg: 'rtsC11', kicker: '',
    head: 'The sin of greed: an excessive desire to want more than what one needs.',
    sub: 'I used to wake up stressed, thinking about what I need to do for the rest of the day.', cta: '' },
  { id: 'C12', name: 'Why rush again', layout: 'cover', bg: 'rtsC12', kicker: '',
    head: 'You’re happy now. You’re at peace. Why do you need to start rushing again?',
    sub: 'That’s made a huge change to the tension that I live by.', cta: '' },
  { id: 'C13', name: 'Breathing wrong', layout: 'cover', bg: 'rtsC13', kicker: '',
    head: 'You breathe every day but you’re still getting it wrong.',
    sub: 'Exhalation is powerful. Breathe out, and focus on the exhalation more.', cta: '' },
  { id: 'C14', name: 'Slowing down time', layout: 'cover', bg: 'rtsC14', kicker: '',
    head: 'Long, slow, controlled exhalation that almost feels like you’re slowing down time.',
    sub: 'I already feel my heart rate slowing.', cta: '' },
  { id: 'C15', name: 'Glamour up my achievements', layout: 'cover', bg: 'rtsC15', kicker: '',
    head: 'There were even points where I would glamour up my achievements to earn his love.',
    sub: 'Can you remember when you had those moments? That overwhelming urge to prove yourself.', cta: '' },
  { id: 'C16', name: 'People-pleaser to self-led', layout: 'type', bg: 'rtsC7', kicker: '',
    head: 'From people-pleaser to self-led.',
    sub: 'I help burnt out men feel seen and rebuild self-worth.', cta: '' },
  { id: 'C17', name: 'What you can control', layout: 'cover', bg: 'rtsC17', kicker: '',
    head: 'You can control how much work and effort you put in, but you can’t control other people’s perspectives.',
    sub: 'The key is to not tie your self-worth to things that you have very little control over.', cta: '' },
  { id: 'C18', name: 'A fine balance', layout: 'cover', bg: 'rtsC18', kicker: '',
    head: 'It’s a fine balance between aiming, but not relentlessly chasing, burning you out.',
    sub: 'It’s knowing that there is nothing wrong with you.', cta: '' },

  /* ---- Static set v1 — 16 Sep 2026 (A1–A3, C1–C8) */
  { id: 'A1.1', name: 'Work ethic, peace', layout: 'graphic', bg: 'rtsA11', kicker: 'Return to Self',
    head: 'Is your relentless work ethic ever going to bring you peace?',
    sub: 'You’re not broken. You’re running on a pattern you built as a kid, because it kept you safe back then.',
    cta: 'See how the 12 weeks work' },
  { id: 'A1.2', name: 'Body still bracing', layout: 'cover', bg: 'rtsA12', kicker: 'Return to Self',
    head: 'Why is your body still bracing for danger that left years ago?',
    sub: 'That’s what kept you safe back then. It isn’t serving you now.',
    cta: 'See how the 12 weeks work' },
  { id: 'A1.3', name: 'Different person', layout: 'graphic', bg: 'rtsA13', kicker: 'Return to Self',
    head: 'Why do you become a different person around certain people?',
    sub: 'Underneath is the real you. The one that’s been behind the mask for years.',
    cta: 'See how the 12 weeks work' },
  { id: 'A1.4', name: 'Exhausted, guilty', layout: 'cover', bg: 'rtsA14', kicker: 'Return to Self',
    head: 'Exhausted, but the moment you stop working you feel guilty.',
    sub: 'Most high performers are running one of two patterns without knowing it. Which one is running you?',
    cta: 'See how the 12 weeks work' },
  { id: 'A2.1', name: 'Before he’s gone', layout: 'split', bg: 'rtsA21', kicker: 'Return to Self',
    head: 'What if he’s gone before you find the right time to say it?',
    sub: 'My dad’s 81. I only really started talking to him three years ago.',
    cta: 'Message me' },
  { id: 'A2.2', name: 'Never about him changing', layout: 'cover', bg: 'rtsA22', kicker: 'Return to Self',
    head: 'Healing my relationship with my dad was never about getting him to change.',
    sub: 'He might never apologise. He might never change. You might still be the one who has to look after him.',
    cta: 'Message me' },
  { id: 'A2.3', name: 'Waiting for the apology', layout: 'archival', bg: 'rtsA23', kicker: 'Return to Self',
    head: 'If you’re waiting for your dad to apologise first, here’s the harder truth.',
    sub: 'He gave me the endurance to keep suppressing my emotions, and the discipline to fight through the pain.',
    cta: 'Message me' },
  { id: 'A3.1', name: 'The one thing', layout: 'cover', bg: 'rtsA31', kicker: 'Return to Self',
    head: 'You can push through almost anything. Except the one thing you actually want to stop.',
    sub: 'The habit isn’t the problem. It never was.',
    cta: 'Message me' },
  { id: 'A3.2', name: 'Still doesn’t stick', layout: 'cover', bg: 'rtsA32', kicker: 'Return to Self',
    head: 'Willpower. Discipline. Starting over. And it still doesn’t stick.',
    sub: 'You’re not weak. You’re fighting the wrong thing.',
    cta: 'Message me' },
  { id: 'A3.3', name: 'Still performing', layout: 'cover', bg: 'rtsA33', kicker: 'Return to Self',
    head: 'Still performing for the people who raised you?',
    sub: 'These habits were formed out of survival. Nothing’s actually threatening you now.',
    cta: 'Message me' },
  { id: 'C1', name: 'Regret', layout: 'cover', bg: 'rtsC1', kicker: '',
    head: 'If my dad died while I was away this year, I’d regret it for the rest of my life.',
    sub: 'We both have love. We just don’t understand each other.', cta: '' },
  { id: 'C2', name: 'Hard conversation', layout: 'split', bg: 'rtsC2', kicker: '',
    head: 'Have the hard conversation.',
    sub: 'That one conversation set the precedent. Since then we’ve had two more.', cta: '' },
  { id: 'C3', name: 'Regulation', layout: 'cover', bg: 'rtsC3', kicker: '',
    head: 'Deep down, everyone’s choice is to stick it through with their parents. They just need regulation.',
    sub: 'Respond with anger and it becomes a legal battle. Respond with love and the odds they respond with love go up.', cta: '' },
  { id: 'C4', name: 'Five minutes', layout: 'cover', bg: 'rtsC4', kicker: '',
    head: 'The 5 minutes you think you don’t have saves you 2 hours of headaches later.',
    sub: 'You think you don’t have time for this. That’s exactly why you need it.', cta: '' },
  { id: 'C5', name: 'Anger', layout: 'cover', bg: 'rtsC5', kicker: '',
    head: 'My 81-year-old karate master father is addicted to one emotion. Anger.',
    sub: 'It gets him to jolt, get up, move, execute. But letting it out is not enough. You’ve got to look at the roots.', cta: '' },
  { id: 'C6', name: 'Pain you avoid', layout: 'cover', bg: 'rtsC6', kicker: '',
    head: 'The pain you avoid doesn’t leave. It moves to the background and runs you.',
    sub: 'I think these things are more felt.', cta: '' },
  { id: 'C7', name: 'Victims of victims', layout: 'type', bg: 'rtsC7', kicker: '',
    head: 'Victims are victims of victims.',
    sub: 'My dad grew up fatherless. Those wounds reached my mum, then his next relationship. Unless they’re understood, they keep recycling into every relationship.', cta: '' },
  { id: 'C8', name: 'It’s cold', layout: 'cover', bg: 'rtsC8', kicker: '',
    head: 'As a kid, “it’s cold” got me beaten. Men don’t complain. Now he’s the one complaining about the cold.',
    sub: 'He’s asking me to understand what I couldn’t understand as a kid. Accepting that role reversal has been the whole battle.', cta: '' },
];
