/* Return to Self static set v1 — 16 Sep 2026.
   One board per video from Nathan's shoot: three ad concepts (hook-matched
   variants) and eight content pieces. Copy is verbatim from the transcripts
   except A1.4's sub and C6's headline, which are paraphrases awaiting sign-off.
   `bg` names a built-in still in assets/statics (photo top, ink below). */
window.__RTS_STATICS__ = [
  { id: 'A1.1', name: 'Work ethic, peace', layout: 'graphic', bg: 'rtsA11', kicker: 'Return to Self',
    head: 'Is your relentless work ethic ever going to bring you peace?',
    sub: 'You’re not broken. You’re running on a pattern you built as a kid, because it kept you safe back then.',
    cta: 'See how the 12 weeks work' },
  { id: 'A1.2', name: 'Body still bracing', layout: 'cover', bg: 'rtsA12', kicker: 'Return to Self',
    head: 'Why is your body still bracing for danger that left years ago?',
    sub: 'That’s what kept you safe back then. It isn’t serving you now.',
    cta: 'See how the 12 weeks work' },
  { id: 'A1.3', name: 'Different person', layout: 'graphic', bg: 'rtsA13', kicker: 'Return to Self',
    head: 'Why do you become a different person around certain people?',
    sub: 'Underneath is the real you. The one that’s been behind the mask for years.',
    cta: 'See how the 12 weeks work' },
  { id: 'A1.4', name: 'Exhausted, guilty', layout: 'cover', bg: 'rtsA14', kicker: 'Return to Self',
    head: 'Exhausted, but the moment you stop working you feel guilty.',
    sub: 'Most high performers are running one of two patterns without knowing it. Which one is running you?',
    cta: 'See how the 12 weeks work' },
  { id: 'A2.1', name: 'Before he’s gone', layout: 'split', bg: 'rtsA21', kicker: 'Return to Self',
    head: 'What if he’s gone before you find the right time to say it?',
    sub: 'My dad’s 81. I only really started talking to him three years ago.',
    cta: 'Message me' },
  { id: 'A2.2', name: 'Never about him changing', layout: 'cover', bg: 'rtsA22', kicker: 'Return to Self',
    head: 'Healing my relationship with my dad was never about getting him to change.',
    sub: 'He might never apologise. He might never change. You might still be the one who has to look after him.',
    cta: 'Message me' },
  { id: 'A2.3', name: 'Waiting for the apology', layout: 'archival', bg: 'rtsA23', kicker: 'Return to Self',
    head: 'If you’re waiting for your dad to apologise first, here’s the harder truth.',
    sub: 'He gave me the endurance to keep suppressing my emotions, and the discipline to fight through the pain.',
    cta: 'Message me' },
  { id: 'A3.1', name: 'The one thing', layout: 'cover', bg: 'rtsA31', kicker: 'Return to Self',
    head: 'You can push through almost anything. Except the one thing you actually want to stop.',
    sub: 'The habit isn’t the problem. It never was.',
    cta: 'Message me' },
  { id: 'A3.2', name: 'Still doesn’t stick', layout: 'cover', bg: 'rtsA32', kicker: 'Return to Self',
    head: 'Willpower. Discipline. Starting over. And it still doesn’t stick.',
    sub: 'You’re not weak. You’re fighting the wrong thing.',
    cta: 'Message me' },
  { id: 'A3.3', name: 'Still performing', layout: 'cover', bg: 'rtsA33', kicker: 'Return to Self',
    head: 'Still performing for the people who raised you?',
    sub: 'These habits were formed out of survival. Nothing’s actually threatening you now.',
    cta: 'Message me' },
  { id: 'C1', name: 'Regret', layout: 'cover', bg: 'rtsC1', kicker: '',
    head: 'If my dad died while I was away this year, I’d regret it for the rest of my life.',
    sub: 'We both have love. We just don’t understand each other.', cta: '' },
  { id: 'C2', name: 'Hard conversation', layout: 'split', bg: 'rtsC2', kicker: '',
    head: 'Have the hard conversation.',
    sub: 'That one conversation set the precedent. Since then we’ve had two more.', cta: '' },
  { id: 'C3', name: 'Regulation', layout: 'cover', bg: 'rtsC3', kicker: '',
    head: 'Deep down, everyone’s choice is to stick it through with their parents. They just need regulation.',
    sub: 'Respond with anger and it becomes a legal battle. Respond with love and the odds they respond with love go up.', cta: '' },
  { id: 'C4', name: 'Five minutes', layout: 'cover', bg: 'rtsC4', kicker: '',
    head: 'The 5 minutes you think you don’t have saves you 2 hours of headaches later.',
    sub: 'You think you don’t have time for this. That’s exactly why you need it.', cta: '' },
  { id: 'C5', name: 'Anger', layout: 'cover', bg: 'rtsC5', kicker: '',
    head: 'My 81-year-old karate master father is addicted to one emotion. Anger.',
    sub: 'It gets him to jolt, get up, move, execute. But letting it out is not enough. You’ve got to look at the roots.', cta: '' },
  { id: 'C6', name: 'Pain you avoid', layout: 'cover', bg: 'rtsC6', kicker: '',
    head: 'The pain you avoid doesn’t leave. It moves to the background and runs you.',
    sub: 'I think these things are more felt.', cta: '' },
  { id: 'C7', name: 'Victims of victims', layout: 'type', bg: 'rtsC7', kicker: '',
    head: 'Victims are victims of victims.',
    sub: 'My dad grew up fatherless. Those wounds reached my mum, then his next relationship. Unless they’re understood, they keep recycling into every relationship.', cta: '' },
  { id: 'C8', name: 'It’s cold', layout: 'cover', bg: 'rtsC8', kicker: '',
    head: 'As a kid, “it’s cold” got me beaten. Men don’t complain. Now he’s the one complaining about the cold.',
    sub: 'He’s asking me to understand what I couldn’t understand as a kid. Accepting that role reversal has been the whole battle.', cta: '' },
];
